# Build Geth in a stock Go builder container
FROM golang:1.13-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /pgp-chain
RUN cd /pgp-chain && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /pgp-chain/build/bin/* /usr/local/bin/

EXPOSE 20666 20655 8547 20668 20668/udp
